# Generated by Django 5.2.7 on 2025-10-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
