# Generated by Django 5.2.7 on 2025-10-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_usertracklastplayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                related_name="playlists",
                through="player.PlaylistItem",
                to="player.track",
            ),
        ),
    ]
