# Generated by Django 5.2.7 on 2025-10-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0006_alter_playlist_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplaybackstate",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="player.playlist",
            ),
        ),
        migrations.AddField(
            model_name="userplaybackstate",
            name="shuffle",
            field=models.BooleanField(default=False),
        ),
    ]
