# Generated by Django 5.2.7 on 2025-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0007_userplaybackstate_playlist_userplaybackstate_shuffle"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
