# Generated by Django 5.2.7 on 2025-10-10 14:18

from django.db import migrations

def populate_file_size(apps, schema_editor):
    Track = apps.get_model('player', 'Track')
    for track in Track.objects.all():
        try:
            if track.file:
                track.file_size = track.file.size
                track.save(update_fields=['file_size'])
        except FileNotFoundError:
            # If the file is missing, we'll just leave the file_size as 0.
            pass

def reverse_populate_file_size(apps, schema_editor):
    # The reverse operation can be a no-op as there's no previous state to restore to.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("player", "0008_track_file_size"),
    ]

    operations = [
        migrations.RunPython(populate_file_size, reverse_populate_file_size),
    ]
