# Generated by Django 5.2.7 on 2025-10-16 21:25

from django.db import migrations
from django.conf import settings

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('player', 'UserProfile')
    for user in User.objects.filter(userprofile__isnull=True):
        UserProfile.objects.create(user=user, storage_limit_gb=settings.DEFAULT_USER_STORAGE_LIMIT_GB)

class Migration(migrations.Migration):

    dependencies = [
        ("player", "0011_userprofile"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
