# Generated by Django 5.2.7 on 2025-10-16 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_populate_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='storage_limit_gb',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
