# Generated by Django 5.2.7 on 2025-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_alter_userprofile_storage_limit_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='order',
            field=models.PositiveIntegerField(default=2147483647),
        ),
    ]
