# Generated by Django 5.2.7 on 2025-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0015_alter_userprofile_storage_limit_gb_userofflinetrack"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplaybackstate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
