# Generated by Django 6.0 on 2025-12-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0015_alter_userprofile_storage_limit_gb_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
