# Generated by Django 5.2.7 on 2026-07-01 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_transcript_processing_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='accessors',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and play (but not edit) this playlist.', related_name='accessible_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
