# Generated by Django 6.0.1 on 2026-01-12 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0016_transcript_processing_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="storage_limit_gb",
            field=models.FloatField(
                default=5.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
