# Generated by Django 5.2.15 on 2026-07-04 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0017_playlist_accessors"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastprogress",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userplaybackstate",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
