# Generated by Django 6.0.1 on 2026-01-13 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0017_alter_userprofile_storage_limit_gb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="storage_limit_gb",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
