# Generated by Django 6.0.1 on 2026-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0018_alter_userprofile_storage_limit_gb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplaybackstate",
            name="last_played_position",
            field=models.FloatField(default=0, null=True),
        ),
    ]
