# Generated by Django 5.2.7 on 2025-10-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="duration",
            field=models.FloatField(default=0),
        ),
    ]
