# Generated by Django 5.2.7 on 2025-10-07 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_track_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_style",
                    models.CharField(
                        choices=[("matte", "Matte"), ("glossy", "Glossy")],
                        default="matte",
                        max_length=10,
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(
                        choices=[
                            ("maroon", "Maroon"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("gray", "Gray"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
